### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Jambon1510** [d0ku/GeckoDriver_ARMv6#3]
Hi d0ku

Whenever I tried to instantiate the driver I end up with the below error
```
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

```
I used the 0.0.19 version I have downloaded thanks to your help #2 

```
pi@raspberrypiB ~ $ geckodriver 
1512053090374	geckodriver	INFO	geckodriver 0.19.0
1512053090489	geckodriver	INFO	Listening on 127.0.0.1:4444

```

**Comment by dezeroku** [comment]
@Jambon1510 Hi, at first It would be nice if you could give me some additional info. I am especially interested in your operating system, Firefox version and do you have X server installed (I mean do you have any GUI on your raspberry). In the meantime you can try to use 0.18.0, I had better results with it.

**Comment by dezeroku** [comment]
Closed because of a lack of an answer.
